# Setup an K3s HA Cluster with HAProxy
---
- name: Updates Servers
  hosts: all
  become: true
  roles:
    - role: ubuntu_update
  tags: ubuntu_update

- name: Setup HAProxy
  hosts: loadbalancers
  become: true
  roles:
    - role: haproxy
  tags: haproxy

- name: Setup keepalived
  hosts: loadbalancers
  become: true
  roles:
    - role: keepalived
  tags: keepalived

- name: Install curl on k3s nodes
  hosts: k3s-nodes
  become: true
  roles:
    - role: curl
  tags: k3s_curl

- name: Setup kmsh on k3s nodes
  hosts: k3s-nodes
  become: true
  roles:
    - role: kmsg
  tags: k3s_kmsg

- name: Init K3s cluster
  hosts: k3s-server-001
  become: true
  roles:
    - role: k3s_server_init
  tags: k3s_server_init

- name: Add K3s server nodes to cluster
  hosts: k3s-server-nodes
  become: true
  roles:
    - role: k3s_server_add
  tags: k3s_server_add

- name: Add K3s agent nodes to cluster
  hosts: k3s-agent-nodes
  become: true
  roles:
    - role: k3s_agent_add
  tags: k3s_agent_add
